// Crytocurrecncies Rest API - Visitar https://docs.nomics.com/#section/Authentication
// key=42d54b10ab1120333958c539ce69578d
export const API_KEY = 'key=demo-26240835858194712a4f8cc0dc635c7a';
export const BASE_URL = 'https://api.nomics.com/v1';

// Action types
export const SEARCH_CRYPTOCURRENCY_START = 'SEARCH_CRYPTOCURRENCY_START';
export const SEARCH_CRYPTOCURRENCY_SUCCEEDED = 'SEARCH_CRYPTOCURRENCY_SUCCEEDED';
export const SEARCH_CRYPTOCURRENCY_FAILED = 'SEARCH_CRYPTOCURRENCY_FAILED';

export const SEARCH_CRYPTOCURRENCY_BY_ID_START = 'SEARCH_CRYPTOCURRENCY_BY_ID_START';
export const SEARCH_CRYPTOCURRENCY_BY_ID_SUCCEEDED = 'SEARCH_CRYPTOCURRENCY_BY_ID_SUCCEEDED';
export const SEARCH_CRYPTOCURRENCY_BY_ID_FAILED = 'SEARCH_CRYPTOCURRENCY_BY_ID_FAILED';
